"use client";

import Link from "next/link";
import styles from "./styles.module.css";


// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <Link className="btn btn-dark ms-3 mt-3 position-fixed" href="/home">
        Return Home
      </Link>
      <div className={styles.centered}>{children}</div>
    </div>
  );
}
