"use client";

import Navbar from "./components/navbar";
import "./styles.css"
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="box">
      <Navbar />
      {children}
    </div>
  );
}
